# NVIDIA GPU Fan Control Configuration

# 开始接管的温度
# Start taking control when the temperature is above this value
start_temperature: 50

# 温度关键点
# The temperature points at which the fan speed will change
temperature_points:
  [ 40, 50, 60, 72 ]

# 每个温度点的风扇转速
# The fan speeds at each temperature point
speeds:
  [ 30, 60, 80, 100 ]

# 检测时间间隔
# The interval at which the temperature is checked
time_interval: 5
